#!/usr/bin/env python3
"""Turn SameBoy's built boot ROMs into a C header.

Embedding them in the module avoids shipping separate binaries and avoids an
Emscripten virtual filesystem. They are tiny (256 B for the DMG family, 2304 B
for the CGB family) and they are SameBoy's own open-source boot ROMs, built
from vendor/sameboy/BootROMs by rgbds.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROMS = [
    "dmg_boot",
    "mgb_boot",
    "cgb_boot",
    "cgb0_boot",
    "agb_boot",
    "sgb_boot",
    "sgb2_boot",
]


def emit(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        rows.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    body = "\n".join(rows)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};\n"


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed-bootroms.py <bootrom-dir> <output-header>", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    out = Path(sys.argv[2])

    parts = [
        "/* Generated by scripts/build-cores/embed-bootroms.py. Do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for name in ROMS:
        path = src / f"{name}.bin"
        if not path.is_file():
            print(f"missing boot ROM: {path}", file=sys.stderr)
            return 1
        parts.append(emit(name, path.read_bytes()))

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts))
    print(f"wrote {out} ({len(ROMS)} boot ROMs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
